sudo: false

dist: trusty

language: php

php:
  - nightly
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install --dev

script: phpunit --configuration=tests/phpunit.xml