sudo: false

dist: trusty

language: php

php:
  - nightly
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5

matrix:
  allow_failures:
    - php: nightly

before_install:
  - curl -s -o $HOME/.phpenv/versions/5.1/bin/phpunit https://phar.phpunit.de/phpunit-5.1.3.phar
  - chmod +x $HOME/.phpenv/versions/5.1/bin/phpunit

before_script:
  - composer install --dev --no-interaction

script: phpunit --configuration=tests/phpunit.xml